### ISSUE TITLE
Zip file for all cad files

### ISSUE THREAD

**Issue by masydoblig** [alanzjl/AlkaidMount#1]
Hi 

Absolutely love this. Great Work im super impressed and loved the you tube video. a video on how the system works would be a great update.

I have been thinking of making the same thing in Solidworks for months.

Do you have a zip file for all the cad Files? i Cant seem to find it if there is one? Also im not used to git hub

Also with the controller board is there a schematic somewhere?

**Comment by alanzjl** [comment]
Hi,

you can download the whole repo as a .zip file. The CAD folder contains all the SolidWorks source files. The PCB folder has the PCB schematic, board design, as well as the CAM files - meaning you can edit them in eagle or just send the CAM files directly to a PCB manufacturer. I’ll close this issue as it’s not something that needs to be fixed. But I’m happy to answer other questions.

Thanks
